# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpatialAnalysisToolbox
                                 A QGIS plugin
This plugin adds some useful algorithms for Spatial Analysis. Some of them are: Moran's I, Local Moran's I, GWR.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-01
        copyright            : (C) 2020 by Parmenion Delialis
        email                : parmeniondelialis@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Parmenion Delialis'
__date__ = '2022-03-01'
__copyright__ = '(C) 2022 by Parmenion Delialis'


def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpatialAnalysisToolbox class from file SpatialAnalysisToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .spatialanalysistoolbox import SpatialAnalysisToolboxPlugin
    return SpatialAnalysisToolboxPlugin()
