
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-22T16:30:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "34212b978e894b57f9ea101ea4f8affb73e1cc0f",
 "version": "4.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
